//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aplikacja.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0")]
    internal sealed partial class Settings1 : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings1 defaultInstance = ((Settings1)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings1())));
        
        public static Settings1 Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color ButtonColor {
            get {
                return ((global::System.Drawing.Color)(this["ButtonColor"]));
            }
            set {
                this["ButtonColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color CheckBoxColor {
            get {
                return ((global::System.Drawing.Color)(this["CheckBoxColor"]));
            }
            set {
                this["CheckBoxColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color ComboBoxColor {
            get {
                return ((global::System.Drawing.Color)(this["ComboBoxColor"]));
            }
            set {
                this["ComboBoxColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color LabelColor {
            get {
                return ((global::System.Drawing.Color)(this["LabelColor"]));
            }
            set {
                this["LabelColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color ProgressBarColor {
            get {
                return ((global::System.Drawing.Color)(this["ProgressBarColor"]));
            }
            set {
                this["ProgressBarColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color RadioButtonColor {
            get {
                return ((global::System.Drawing.Color)(this["RadioButtonColor"]));
            }
            set {
                this["RadioButtonColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color TextBoxColor {
            get {
                return ((global::System.Drawing.Color)(this["TextBoxColor"]));
            }
            set {
                this["TextBoxColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color PropertiesColor {
            get {
                return ((global::System.Drawing.Color)(this["PropertiesColor"]));
            }
            set {
                this["PropertiesColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color ButtonTColor {
            get {
                return ((global::System.Drawing.Color)(this["ButtonTColor"]));
            }
            set {
                this["ButtonTColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color CheckBoxTColor {
            get {
                return ((global::System.Drawing.Color)(this["CheckBoxTColor"]));
            }
            set {
                this["CheckBoxTColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color ComboBoxTColor {
            get {
                return ((global::System.Drawing.Color)(this["ComboBoxTColor"]));
            }
            set {
                this["ComboBoxTColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color LabelTColor {
            get {
                return ((global::System.Drawing.Color)(this["LabelTColor"]));
            }
            set {
                this["LabelTColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color ProgressBarTColor {
            get {
                return ((global::System.Drawing.Color)(this["ProgressBarTColor"]));
            }
            set {
                this["ProgressBarTColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color RadioButtonTColor {
            get {
                return ((global::System.Drawing.Color)(this["RadioButtonTColor"]));
            }
            set {
                this["RadioButtonTColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color TextBoxTColor {
            get {
                return ((global::System.Drawing.Color)(this["TextBoxTColor"]));
            }
            set {
                this["TextBoxTColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color PropertiesTColor {
            get {
                return ((global::System.Drawing.Color)(this["PropertiesTColor"]));
            }
            set {
                this["PropertiesTColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color ThisColor {
            get {
                return ((global::System.Drawing.Color)(this["ThisColor"]));
            }
            set {
                this["ThisColor"] = value;
            }
        }
    }
}
